services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: ./services/auth-service
    container_name: ecom-auth
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shop
      DB_PASSWORD: shop
      DB_NAME: shop
      JWT_SECRET: ci-jwt-secret
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

  product-service:
    build:
      context: ./services/product-service
    container_name: ecom-product
    environment:
      NODE_ENV: production
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shop
      DB_PASSWORD: shop
      DB_NAME: shop
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3002:3002"

  order-service:
    build:
      context: ./services/order-service
    container_name: ecom-order
    environment:
      NODE_ENV: production
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shop
      DB_PASSWORD: shop
      DB_NAME: shop
      PRODUCT_SERVICE_URL: http://product-service:3002
    depends_on:
      postgres:
        condition: service_healthy
      product-service:
        condition: service_started
    ports:
      - "3003:3003"

  notification-service:
    build:
      context: ./services/notification-service
    container_name: ecom-notification
    environment:
      NODE_ENV: production
      PORT: 3004
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shop
      DB_PASSWORD: shop
      DB_NAME: shop
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "3004:3004"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  frontend:
    build:
      context: ./frontend
    container_name: ecom-frontend
    depends_on:
      - nginx
    ports:
      - "5173:8080"

  nginx:
    build:
      context: ./nginx
    container_name: ecom-nginx
    depends_on:
      - auth-service
      - product-service
      - order-service
      - notification-service
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  rabbitmq_data:                     